"""SecurityMasker proxy ASGI app (ADR-0006; hardened per doc/06-Issue.md P0).

Routes Codex (OpenAI Responses) and Claude Code (Anthropic Messages) through the
masking core. Security gates (external-send is only allowed after masking):

- explicit route allowlist — unknown routes are refused locally, never forwarded;
- request validation — non-JSON-object, malformed, oversized, or unsupported
  Content-Encoding bodies are refused locally before anything leaves;
- header hygiene — internal `X-SecurityMasker-*` headers are stripped; client auth
  is passed through to the correct upstream, never logged (§25);
- readiness (`/ready`) is distinct from liveness (`/health`).

One handler invocation resolves the session, masks the request, forwards it, and
restores the response — owning both directions.
"""

from __future__ import annotations

import json
from collections.abc import Awaitable, Callable
from typing import Any

from starlette.applications import Starlette
from starlette.requests import Request
from starlette.responses import JSONResponse, Response
from starlette.routing import Route

from securitymasker.detectors.existing_alias import contains_alias_shape
from securitymasker.engine import MaskingEngine, iter_strings
from securitymasker.errors import SecurityMaskerError
from securitymasker.gateway.forwarder import forward_buffered, forward_streaming
from securitymasker.gateway.responses_stream import ResponsesStreamProcessor
from securitymasker.gateway.runtime import GatewayRuntime
from securitymasker.gateway.session import namespaced_key, resolve_session, resolve_tenant
from securitymasker.logging import get_logger
from securitymasker.models import MaskingSession
from securitymasker.protocols import anthropic_messages, openai_responses
from securitymasker.streaming.anthropic_stream import AnthropicStreamProcessor

_log = get_logger(component="securitymasker.gateway")

# Max request body accepted before masking (doc/06 P0-5). Module-level so it can be
# tuned/overridden; a hard cap protects the detectors and the event loop (§32).
MAX_BODY_BYTES = 10 * 1024 * 1024
_INTERNAL_HEADER_PREFIX = "x-securitymasker-"


def _error(status: int, code: str, message: str) -> JSONResponse:
    # Never echo the request body/values in an error (§25).
    return JSONResponse({"error": {"message": message, "type": code, "code": str(status)}},
                        status_code=status)


def _payload_has_alias_shape(data: dict[str, Any]) -> bool:
    return any(contains_alias_shape(s) for s in iter_strings(data))


# Headers forwarded to ANY upstream. Deny-by-default: anything not listed here (or
# in the provider set below) is dropped, so a custom header can neither leak a
# secret nor smuggle data past the masker (doc/06 P0-4).
_COMMON_HEADERS = frozenset({
    "accept", "accept-encoding", "accept-language", "content-type", "content-length",
    "user-agent",
})

# Provider-scoped headers. `x-api-key` is Anthropic's and must never reach OpenAI;
# `openai-*`/`chatgpt-*` are OpenAI's and must never reach Anthropic (doc/06 P0-3).
# `authorization` is Bearer for BOTH providers, so it is forwarded only to the
# upstream the client's own route selected — never copied across providers.
_OPENAI_HEADERS = frozenset({
    "authorization", "openai-organization", "openai-project", "openai-beta",
    "chatgpt-account-id", "originator", "session_id",
})
_ANTHROPIC_HEADERS = frozenset({
    "authorization", "x-api-key", "anthropic-version", "anthropic-beta",
    "anthropic-dangerous-direct-browser-access",
})

PROVIDER_HEADERS: dict[str, frozenset[str]] = {
    "openai": _OPENAI_HEADERS,
    "anthropic": _ANTHROPIC_HEADERS,
}

# Auth headers are passed through to their own provider but never masked, stored,
# or logged (§25) — and never leak-scanned into an error message.
_AUTH_HEADERS = frozenset({"authorization", "x-api-key"})

# Generated by the client/proxy transport rather than carrying user content; they
# legitimately hold IPs and hostnames, so they are not leak-scanned.
_TRANSPORT_HEADERS = frozenset({
    "host", "connection", "content-length", "accept-encoding", "accept",
    "accept-language", "user-agent", "via", "forwarded",
    "x-forwarded-for", "x-forwarded-host", "x-forwarded-proto", "x-real-ip",
})


def _client_headers(request: Request, provider: str) -> dict[str, str]:
    """Allowlisted headers for ``provider``; everything else is dropped."""
    allowed = _COMMON_HEADERS | PROVIDER_HEADERS.get(provider, frozenset())
    return {k: v for k, v in request.headers.items() if k.lower() in allowed}


async def _read_json_object(request: Request) -> tuple[dict[str, Any] | None, JSONResponse | None]:
    """Validate + parse the request body to a JSON object, or return a local error.

    Refuses (no forward) on unsupported Content-Encoding/Type, oversized bodies,
    malformed JSON, or non-object JSON (doc/06 P0-2/P0-5).
    """
    encoding = request.headers.get("content-encoding", "").strip().lower()
    if encoding and encoding != "identity":
        return None, _error(415, "unsupported_content_encoding",
                            f"Content-Encoding {encoding!r} is not supported.")
    ctype = request.headers.get("content-type", "")
    if ctype and "json" not in ctype.lower():
        return None, _error(415, "unsupported_media_type",
                            "Only application/json request bodies are supported.")
    raw = await request.body()
    if len(raw) > MAX_BODY_BYTES:
        return None, _error(413, "payload_too_large",
                            f"Request body exceeds the {MAX_BODY_BYTES}-byte limit.")
    try:
        data = json.loads(raw) if raw else {}
    except (json.JSONDecodeError, UnicodeDecodeError):
        return None, _error(400, "invalid_json", "Request body is not valid JSON.")
    if not isinstance(data, dict):
        return None, _error(400, "invalid_body", "Request body must be a JSON object.")
    return data, None


async def health(request: Request) -> JSONResponse:
    """Liveness: the process is up."""
    return JSONResponse({"ok": True})


async def ready(request: Request) -> JSONResponse:
    """Readiness: the masking engine and store are available (doc/06 P0-1)."""
    rt: GatewayRuntime = request.app.state.runtime
    if rt.engine is None:
        return JSONResponse({"ready": False, "reason": "masking engine not configured"},
                            status_code=503)
    return JSONResponse({"ready": True})


async def _handle(
    request: Request,
    *,
    upstream: str,
    path: str,
    provider: str,
    mask: Callable[[MaskingEngine, MaskingSession, dict[str, Any]], Awaitable[None]],
    restore_dict: Callable[[MaskingEngine, MaskingSession, dict[str, Any]], None],
    stream_processor: Callable[..., Any],
) -> Response:
    rt: GatewayRuntime = request.app.state.runtime
    url = f"{upstream}{path}"
    headers = _client_headers(request, provider)

    if rt.engine is None:
        # Dev-only transparent mode (config-required by default; see runtime).
        return await forward_streaming(request.method, url, headers, await request.body())

    data, err = await _read_json_object(request)
    if err is not None or data is None:
        return err or _error(400, "invalid_body", "Request body must be a JSON object.")

    tenant = resolve_tenant(rt.mode, rt.tenant_header, request.headers)
    if tenant is None:
        # Multitenant mode with no trusted tenant: fail closed rather than risk
        # sharing one tenant's alias table with another (doc/06 P0-9).
        _log.warning("sm_block_no_tenant", path=path)
        return _error(403, "tenant_required", "A trusted tenant identity is required.")

    resolved = resolve_session(request.headers, data)
    if not resolved.stable and _payload_has_alias_shape(data):
        # Prior-turn aliases but no stable session to restore them: block instead
        # of silently starting a fresh session and corrupting the turn (P1-1).
        _log.warning("sm_block_unresolved_session", path=path)
        return _error(409, "session_unresolved",
                      "Request references prior aliases but no stable session id was provided.")

    store_key = namespaced_key(tenant, resolved.session_id)
    try:
        # Lock first so get/create/mask/save share one exclusion window — two
        # workers can't fork the same session's alias table (doc/06 P1-9).
        async with rt.store.lock(store_key):
            session = await rt.store.get_or_create(store_key, tenant_id=tenant)
            await mask(rt.engine, session, data)
            await rt.store.save(session)
        # Final block-only guard over the whole masked payload (doc/06 P0-4): a
        # registered secret in an unknown/structural field must never be forwarded.
        await rt.engine.assert_no_leak_in_payload(data, session=session, request_id=store_key)
        # Same guard over every INCOMING non-auth header — not just the allowlisted
        # subset — so a secret placed in a header is refused outright rather than
        # silently dropped (doc/06 P0-4). Provider auth headers are excluded: they
        # are the client's own credential for this upstream and must never be
        # scanned into an error or log (§25). Transport headers are excluded too:
        # they are generated by the client/proxy, not user content.
        await rt.engine.assert_no_leak_in_headers(
            {k: v for k, v in request.headers.items()
             if k.lower() not in _AUTH_HEADERS and k.lower() not in _TRANSPORT_HEADERS},
            session=session, request_id=store_key,
        )
    except SecurityMaskerError as exc:
        _log.warning("sm_block", path=path)
        return _error(400, "securitymasker_blocked", str(exc))

    masked = json.dumps(data, ensure_ascii=False).encode("utf-8")
    if data.get("stream"):
        proc = stream_processor(rt.engine.literal_restorations(session),
                                rt.engine.make_restorer(session),
                                rt.engine.tool_trust)
        return await forward_streaming(request.method, url, headers, masked, proc)

    status, resp_headers, content = await forward_buffered(request.method, url, headers, masked)
    resp = None
    try:
        parsed = json.loads(content) if content else None
        resp = parsed if isinstance(parsed, dict) else None
    except (json.JSONDecodeError, UnicodeDecodeError):
        resp = None
    if resp is not None:
        restore_dict(rt.engine, session, resp)
        return Response(json.dumps(resp, ensure_ascii=False), status_code=status,
                        media_type="application/json")
    return Response(content, status_code=status, media_type=resp_headers.get("content-type"))


async def handle_responses(request: Request) -> Response:
    rt: GatewayRuntime = request.app.state.runtime
    return await _handle(request, upstream=rt.openai_upstream, path="/responses",
                         provider="openai",
                         mask=openai_responses.mask_request,
                         restore_dict=openai_responses.restore_response,
                         stream_processor=ResponsesStreamProcessor)


async def handle_messages(request: Request) -> Response:
    rt: GatewayRuntime = request.app.state.runtime
    return await _handle(request, upstream=rt.anthropic_upstream, path="/v1/messages",
                         provider="anthropic",
                         mask=anthropic_messages.mask_request,
                         restore_dict=anthropic_messages.restore_response,
                         stream_processor=AnthropicStreamProcessor)


async def handle_models(request: Request) -> Response:
    """Transparent, mask-free passthrough for the model list (safe GET, doc/06 P0-3)."""
    rt: GatewayRuntime = request.app.state.runtime
    url = f"{rt.openai_upstream}/models"
    return await forward_streaming(
        request.method, url, _client_headers(request, "openai"), await request.body()
    )


def create_app(runtime: GatewayRuntime | None = None) -> Starlette:
    # Explicit allowlist only — no catch-all; unknown routes 404 locally (P0-3).
    routes = [
        Route("/health", health, methods=["GET"]),
        Route("/ready", ready, methods=["GET"]),
        Route("/responses", handle_responses, methods=["POST"]),
        Route("/v1/responses", handle_responses, methods=["POST"]),
        Route("/messages", handle_messages, methods=["POST"]),
        Route("/v1/messages", handle_messages, methods=["POST"]),
        Route("/models", handle_models, methods=["GET"]),
        Route("/v1/models", handle_models, methods=["GET"]),
    ]
    app = Starlette(routes=routes)
    app.state.runtime = runtime or GatewayRuntime.from_env()
    return app
